/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 17-Apr-2024 20:08:50
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 67
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2022b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 67;
const float B[67] = {
  0.0006304471754,-0.004008303862, 0.009432750754, -0.01007932052, 0.001728607924,
    0.00614040345, -0.00217596232,-0.005610015709, 0.001797625213, 0.006315851118,
   -0.00123940839,-0.007589591201,0.0003790328337, 0.009250257164,0.0009341173572,
   -0.01118328515,-0.002909840085,  0.01332560275, 0.005766998045, -0.01559044141,
  -0.009800358675,   0.0178699512,  0.01547213644, -0.02006125636, -0.02357903682,
    0.02205458656,  0.03579010814, -0.02374285646, -0.05645575747,  0.02502862364,
     0.1016580835, -0.02583206818,  -0.3168072104,   0.5261050463,  -0.3168072104,
   -0.02583206818,   0.1016580835,  0.02502862364, -0.05645575747, -0.02374285646,
    0.03579010814,  0.02205458656, -0.02357903682, -0.02006125636,  0.01547213644,
     0.0178699512,-0.009800358675, -0.01559044141, 0.005766998045,  0.01332560275,
  -0.002909840085, -0.01118328515,0.0009341173572, 0.009250257164,0.0003790328337,
  -0.007589591201, -0.00123940839, 0.006315851118, 0.001797625213,-0.005610015709,
   -0.00217596232,  0.00614040345, 0.001728607924, -0.01007932052, 0.009432750754,
  -0.004008303862,0.0006304471754
};
